### ISSUE TITLE
Good Project!

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [LeslieCorrea/Xamarin-Forms-Shopping-Cart#1]
you're doing a great job, just the look of the app that is not very nice, when will it be ready do you have a prediction of when it will end?

**Comment by LeslieCorrea** [comment]
Hi Anderson,

I am working on the UI part, it will be completed soon.

Thanks and Regards
Leslie Correa

**Comment by andersonvieiragomeslopes** [comment]
Congratulations, is there any material available that helps me build a shopping cart like yours? I'm in great need of it.

**Comment by LeslieCorrea** [comment]
Hi Anderson,

For badge on a toolbar item check https://github.com/LeslieCorrea/Xamarin-Forms-Shopping-Cart/tree/master/ShoppingCarts/ShoppingCarts/ContentView in my repo,for an example check https://social.technet.microsoft.com/wiki/contents/articles/37733.xamarin-shopping-cart-counter-in-forms-navigation-bar.aspx 

If want full project you can check https://grialkit.com/ it has mostly all kind of UI but it is paid.

**Comment by LeslieCorrea** [comment]
Hi Anderson,

I have updated most of the UI, please check the latest commits.

-Leslie Correa
